spring.application.name=DevOpsMonitoringSaaS

# Server
server.port=8080

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,prometheus

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/devopsmonitoring
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=0000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT (use a long random secret in production)
jwt.secret=devops-monitoring-saas-jwt-secret-key-min-256-bits-for-hs256-algorithm
